# Generated by Django 5.1 on 2025-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='En cours', max_length=50)),
                ('localisation', models.CharField(max_length=255)),
                ('type_signalement', models.CharField(max_length=50)),
                ('utilisateur_id', models.IntegerField()),
                ('commune_id', models.IntegerField()),
            ],
        ),
    ]
