# Generated by Django 5.1 on 2025-05-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='titre',
            new_name='objet',
        ),
    ]
