# Generated by Django 5.1 on 2025-05-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0002_rename_titre_signalement_objet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='commune_id',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='utilisateur_id',
        ),
        migrations.AddField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
