# Generated by Django 5.1 on 2025-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0003_remove_signalement_commune_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='photo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
