# Generated by Django 5.1 on 2025-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0004_signalement_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='type_signalement',
            field=models.CharField(choices=[('dechets', 'Déchets'), ('pollution', 'Pollution'), ('climat', 'Climat')], max_length=50),
        ),
    ]
