# Generated by Django 5.1 on 2025-05-23 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0002_remove_commune_description_commune_region'),
        ('signalement', '0005_alter_signalement_type_signalement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-date_signalement']},
        ),
        migrations.AddField(
            model_name='signalement',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communes.commune'),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traite', 'Traité')], default='en_attente', max_length=50),
        ),
    ]
