# Generated by Django 4.2.7 on 2025-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalement', '0006_alter_signalement_options_signalement_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('rejeté', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=50),
        ),
    ]
