# Generated by Django 5.2 on 2025-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
