# Generated by Django 5.1 on 2025-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_code_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Citoyens', 'Citoyens'), ('ONG', 'ONG'), ('Entreprise', 'Entreprise'), ('CTD', 'CTD')], default='Citoyens', max_length=15, verbose_name='rôle'),
        ),
    ]
