# Generated by Django 5.1 on 2025-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Citoyens', 'Citoyens'), ('ONG', 'ONG'), ('Entreprise', 'Entreprise'), ('ctd', 'CTD')], default='Citoyens', max_length=15, verbose_name='rôle'),
        ),
    ]
