# Generated by Django 5.1.3 on 2025-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='description',
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.CharField(default='null', max_length=100, verbose_name='region'),
            preserve_default=False,
        ),
    ]
