# Generated by Django 5.1 on 2025-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0002_remove_commune_description_commune_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='commune',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
