# Generated by Django 4.2.7 on 2025-07-04 09:22

from django.db import migrations, models
import django.db.models.deletion
import zones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la zone')),
                ('type', models.CharField(choices=[('innondations', 'Inondations'), ('secheresse', 'Sécheresse'), ('glissement de terrain', 'Glissement de terrain'), ("cours d'eau", "Cours d'eau"), ('zone agricole', 'Zone agricole'), ('centres de santé', 'Centres de santé'), ('apparition des insectes nuisibles', 'Apparition des insectes nuisibles')], max_length=50, verbose_name='Type de risque')),
                ('description', models.TextField(verbose_name='Description')),
                ('coordinates', models.JSONField(help_text='Coordonnées du polygone au format GeoJSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone à risque',
                'verbose_name_plural': 'Zones à risque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskZoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=zones.models.zone_image_upload_path, verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('risk_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zones.riskzone', verbose_name='Zone à risque')),
            ],
            options={
                'verbose_name': 'Image de zone à risque',
                'verbose_name_plural': 'Images de zones à risque',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
